import aiohttp
import asyncio
import logging
import re
from .chat import Chat as Chat, Sender as Sender
from .reloader import run_with_reloader as run_with_reloader
from .types_ import TG_CallbackQueryOpts as TG_CallbackQueryOpts, TG_CallbackQuerySrc as TG_CallbackQuerySrc, TG_ChosenInlineResultSrc as TG_ChosenInlineResultSrc, TG_EditMessageReplyMarkupOpts as TG_EditMessageReplyMarkupOpts, TG_EditMessageTextOpts as TG_EditMessageTextOpts, TG_File as TG_File, TG_GetUserProfilePhotosOpts as TG_GetUserProfilePhotosOpts, TG_InlineQueryAnswerOpts as TG_InlineQueryAnswerOpts, TG_InlineQueryResult as TG_InlineQueryResult, TG_InlineQuerySrc as TG_InlineQuerySrc, TG_Location as TG_Location, TG_Message as TG_Message, TG_MessageResponse as TG_MessageResponse, TG_PreCheckoutQuerySrc as TG_PreCheckoutQuerySrc, TG_SendMessageOpts as TG_SendMessageOpts, TG_SetWebhookOpts as TG_SetWebhookOpts, TG_Update as TG_Update, TG_UpdateResponse as TG_UpdateResponse, TG_User as TG_User
from aiohttp import ClientResponse as ClientResponse, web
from aiohttp.client import _RequestContextManager
from collections.abc import Awaitable
from typing import Any, Callable, Unpack, overload

CommandHandler = Callable[["Chat", re.Match[str]], Any]
CommandDecorator = Callable[[CommandHandler], CommandHandler]
DefaultHandler = Callable[["Chat", "TG_Message"], Any]
DefaultInlineHandler = Callable[["InlineQuery"], Any]
RegexInlineHandler = Callable[["InlineQuery", re.Match[str]], Any]
RegexInlineDecorator = Callable[[RegexInlineHandler], RegexInlineHandler]
DefaultChosenInlineResultHandler = Callable[["ChosenInlineResult"], Any]
RegexChosenInlineResultHandler = Callable[["ChosenInlineResult", re.Match[str]], Any]
RegexChosenInlineResultDecorator = Callable[[RegexChosenInlineResultHandler], RegexChosenInlineResultHandler]
DefaultCallbackHandler = Callable[["Chat | None", "CallbackQuery"], Any]
RegexCallbackHandler = Callable[["Chat | None", "CallbackQuery", re.Match[str]], Any]
RegexCallbackDecorator = Callable[[RegexCallbackHandler], RegexCallbackHandler]
DefaultCheckoutHandler = Callable[["PreCheckoutQuery"], Any]
RegexCheckoutHandler = Callable[["PreCheckoutQuery", re.Match[str]], Any]
RegexCheckoutDecorator = Callable[[RegexCheckoutHandler], RegexCheckoutHandler]
MessageHandler = Callable[["Chat", Any], Any]
MessageHandlerDecorator = Callable[[MessageHandler], MessageHandler]
API_URL: str
API_TIMEOUT: int
RETRY_TIMEOUT: int
RETRY_CODES: list[int]
MESSAGE_TYPES: list[str]
MESSAGE_UPDATES: list[str]
logger: logging.Logger

class Bot:
    api_token: str
    api_timeout: int
    name: str | None
    json_serialize: Callable[..., str]
    json_deserialize: Callable[..., Any]
    default_in_groups: bool
    def __init__(self, api_token: str, api_timeout: int = ..., name: str | None = None, json_serialize: Callable[..., str] = ..., json_deserialize: Callable[..., Any] = ..., default_in_groups: bool = False, connector: aiohttp.BaseConnector | None = None) -> None: ...
    async def loop(self) -> None: ...
    def run(self, debug: bool = False, reload: bool | None = None) -> None: ...
    def run_webhook(self, webhook_url: str, **options: Unpack[TG_SetWebhookOpts]) -> None: ...
    def stop_webhook(self) -> None: ...
    def add_command(self, regexp: str, fn: CommandHandler) -> None: ...
    def command(self, regexp: str) -> CommandDecorator: ...
    def default(self, callback: DefaultHandler) -> DefaultHandler: ...
    def add_inline(self, regexp: str, fn: RegexInlineHandler) -> None: ...
    @overload
    def inline(self, callback: DefaultInlineHandler) -> DefaultInlineHandler: ...
    @overload
    def inline(self, callback: str) -> RegexInlineDecorator: ...
    def add_chosen_inline_result_callback(self, regexp: str, fn: RegexChosenInlineResultHandler) -> None: ...
    @overload
    def chosen_inline_result_callback(self, callback: DefaultChosenInlineResultHandler) -> DefaultChosenInlineResultHandler: ...
    @overload
    def chosen_inline_result_callback(self, callback: str) -> RegexChosenInlineResultDecorator: ...
    def add_callback(self, regexp: str, fn: RegexCallbackHandler) -> None: ...
    @overload
    def callback(self, callback: DefaultCallbackHandler) -> DefaultCallbackHandler: ...
    @overload
    def callback(self, callback: str) -> RegexCallbackDecorator: ...
    def add_checkout(self, regexp: str, fn: RegexCheckoutHandler) -> None: ...
    @overload
    def checkout(self, callback: DefaultCheckoutHandler) -> DefaultCheckoutHandler: ...
    @overload
    def checkout(self, callback: str) -> RegexCheckoutDecorator: ...
    def handle(self, msg_type: str) -> MessageHandlerDecorator: ...
    def channel(self, channel_name: str) -> Chat: ...
    def private(self, user_id: str) -> Chat: ...
    def group(self, group_id: str) -> Chat: ...
    def api_call(self, method: str, **params: Any) -> Awaitable[Any]: ...
    async def get_me(self) -> TG_User: ...
    async def leave_chat(self, chat_id: int | str) -> bool: ...
    def send_message(self, chat_id: int | str, text: str, **options: Unpack[TG_SendMessageOpts]) -> Awaitable[TG_MessageResponse]: ...
    def edit_message_text(self, chat_id: int | str, message_id: int, text: str, **options: Unpack[TG_EditMessageTextOpts]) -> Awaitable[TG_MessageResponse]: ...
    def edit_message_reply_markup(self, chat_id: int | str, message_id: int, reply_markup: str, **options: Unpack[TG_EditMessageReplyMarkupOpts]) -> Awaitable[Any]: ...
    async def get_file(self, file_id: int) -> TG_File: ...
    def download_file(self, file_path: str, range: str | None = None) -> _RequestContextManager: ...
    def get_user_profile_photos(self, user_id: int, **options: Unpack[TG_GetUserProfilePhotosOpts]) -> Awaitable[Any]: ...
    def stop(self) -> None: ...
    async def webhook_handle(self, request: web.Request) -> web.Response: ...
    def create_webhook_app(self, path: str, loop: asyncio.AbstractEventLoop | None = None) -> web.Application: ...
    def set_webhook(self, webhook_url: str, **options: Unpack[TG_SetWebhookOpts]) -> Awaitable[Any]: ...
    def delete_webhook(self) -> Awaitable[Any]: ...
    def on_cleanup(self, action: Callable[[], Any]) -> None: ...
    @property
    def session(self) -> aiohttp.ClientSession: ...

class InlineQuery:
    bot: Bot
    sender: Sender
    query_id: str
    query: str
    def __init__(self, bot: Bot, src: TG_InlineQuerySrc) -> None: ...
    def answer(self, results: list[TG_InlineQueryResult], **options: Unpack[TG_InlineQueryAnswerOpts]): ...

class ChosenInlineResult:
    bot: Bot
    sender: Sender
    result_id: str
    location: TG_Location | None
    inline_message_id: str | None
    query: str
    def __init__(self, bot: Bot, src: TG_ChosenInlineResultSrc) -> None: ...

class CallbackQuery:
    bot: Bot
    query_id: str
    data: str
    src: TG_CallbackQuerySrc
    def __init__(self, bot: Bot, src: TG_CallbackQuerySrc) -> None: ...
    def answer(self, **options: Unpack[TG_CallbackQueryOpts]): ...

class PreCheckoutQuery:
    bot: Bot
    sender: Sender
    query_id: str
    currency: str
    total_amount: int
    invoice_payload: str
    def __init__(self, bot: Bot, src: TG_PreCheckoutQuerySrc) -> None: ...
    def answer(self, error_message: str | None = None): ...

class BotApiError(RuntimeError):
    response: ClientResponse
    def __init__(self, *args: object, response: aiohttp.ClientResponse) -> None: ...
