import logging
from .bot import Bot as Bot
from .types_ import TG_BoolResponse as TG_BoolResponse, TG_EditMessageTextOpts as TG_EditMessageTextOpts, TG_GetChatAdministratorResponse as TG_GetChatAdministratorResponse, TG_GetChatMemberCountResponse as TG_GetChatMemberCountResponse, TG_GetChatMemberResponse as TG_GetChatMemberResponse, TG_GetChatResponse as TG_GetChatResponse, TG_InlineKeyboardMarkup as TG_InlineKeyboardMarkup, TG_MaybeInaccessibleMessage as TG_MaybeInaccessibleMessage, TG_MessageResponse as TG_MessageResponse, TG_ReplyMarkupOpts as TG_ReplyMarkupOpts, TG_SendAudioOpts as TG_SendAudioOpts, TG_SendContactOpts as TG_SendContactOpts, TG_SendDocumentOpts as TG_SendDocumentOpts, TG_SendFileInput as TG_SendFileInput, TG_SendLocationOpts as TG_SendLocationOpts, TG_SendMediaGroupOpts as TG_SendMediaGroupOpts, TG_SendMediaGroupResponse as TG_SendMediaGroupResponse, TG_SendMessageOpts as TG_SendMessageOpts, TG_SendPhotoOpts as TG_SendPhotoOpts, TG_SendStickerOpts as TG_SendStickerOpts, TG_SendVenueOpts as TG_SendVenueOpts, TG_SendVideoOpts as TG_SendVideoOpts, TG_SendVoiceOpts as TG_SendVoiceOpts
from collections.abc import Awaitable
from typing import Any, Literal, Unpack

logger: logging.Logger

class Chat:
    def send_text(self, text: str, **options: Unpack[TG_SendMessageOpts]) -> Awaitable[TG_MessageResponse]: ...
    def reply(self, text: str, markup: TG_ReplyMarkupOpts | None = None, parse_mode: Literal['Markdown', 'HTML'] | None = None) -> Awaitable[TG_MessageResponse]: ...
    def edit_text(self, message_id: int, text: str, markup: TG_InlineKeyboardMarkup | None = None, parse_mode: Literal['Markdown', 'HTML'] | None = None) -> Awaitable[TG_MessageResponse]: ...
    def edit_reply_markup(self, message_id: int, markup: TG_ReplyMarkupOpts) -> Awaitable[TG_MessageResponse]: ...
    def get_chat(self) -> Awaitable[TG_GetChatResponse]: ...
    def get_chat_administrators(self) -> Awaitable[TG_GetChatAdministratorResponse]: ...
    def get_chat_members_count(self) -> Awaitable[TG_GetChatMemberCountResponse]: ...
    def get_chat_member(self, user_id: int) -> Awaitable[TG_GetChatMemberResponse]: ...
    def send_sticker(self, sticker: TG_SendFileInput, **options: Unpack[TG_SendStickerOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_audio(self, audio: TG_SendFileInput, **options: Unpack[TG_SendAudioOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_photo(self, photo: TG_SendFileInput, caption: str = '', **options: Unpack[TG_SendPhotoOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_video(self, video: TG_SendFileInput, caption: str = '', **options: Unpack[TG_SendVideoOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_document(self, document: TG_SendFileInput, caption: str = '', **options: Unpack[TG_SendDocumentOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_voice(self, voice: TG_SendFileInput, **options: Unpack[TG_SendVoiceOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_location(self, latitude: float, longitude: float, **options: Unpack[TG_SendLocationOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_venue(self, latitude: float, longitude: float, title: str | bytes, address: str | bytes, **options: Unpack[TG_SendVenueOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_contact(self, phone_number: str, first_name: str | bytes, **options: Unpack[TG_SendContactOpts]) -> Awaitable[TG_MessageResponse]: ...
    def send_chat_action(self, action: Literal['typing', 'upload_photo', 'record_video', 'upload_video', 'record_audio', 'upload_audio', 'upload_document', 'find_location']) -> Awaitable[TG_BoolResponse]: ...
    def send_media_group(self, media: str, disable_notification: bool = False, reply_to_message_id: int | None = None, **options: Unpack[TG_SendMediaGroupOpts]) -> Awaitable[TG_SendMediaGroupResponse]: ...
    def forward_message(self, from_chat_id: int, message_id: int) -> Awaitable[TG_MessageResponse]: ...
    def kick_chat_member(self, user_id: int) -> Awaitable[TG_BoolResponse]: ...
    def unban_chat_member(self, user_id: int) -> Awaitable[TG_BoolResponse]: ...
    def delete_message(self, message_id: int) -> Awaitable[TG_BoolResponse]: ...
    def is_group(self) -> bool: ...
    bot: Bot
    message: TG_MaybeInaccessibleMessage | None
    sender: Sender
    id: int | str
    type: Literal['private', 'group', 'supergroup', 'channel']
    def __init__(self, bot: Bot, chat_id: int | str, chat_type: Literal['private', 'group', 'supergroup', 'channel'] = 'private', src_message: TG_MaybeInaccessibleMessage | None = None) -> None: ...
    @staticmethod
    def from_message(bot: Bot, message: TG_MaybeInaccessibleMessage) -> Chat: ...

class Sender(dict[str, Any]): ...
